### ISSUE TITLE
Bad Request - The number of request header fields exceeds this server's limit

### ISSUE THREAD

**Issue by johnwiesel** [bigcommerce/bigcommerce-api-php#96] opened 2014-04-25 12:14 UTC
When issuing a get request after getCollection() call using Bigcommerce\Api\Connection, I experience a 400 response with an empty message field in the Bigcommerce\Api\Error exception.
When dumping the curl response, the error message from the server is 
 Bad Request - The number of request header fields exceeds this server's limit.

This was fixed for me by resetting the headers array before the get:
```php
	public function get($url, $query=false)
	{
                $this->headers = array();
                $this->initializeRequest();
```
Interestingly, this did occurred only on my Ubuntu 12.04.3 LTS, but not on my Ubuntu 14.04 LTS.

Not working on:
Ubuntu 12.04.3 LTS
curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

Seems to work fine on:
Ubuntu 14.04 LTS
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

Thanks for looking into this..

**Comment by aleachjr** [comment] 2015-02-17 18:51
I am unable to reproduce this issue. Closing as there has been no recent response. Please open a new issue if you continue to experience.

**Closed by aleachjr** 2015-02-17 18:51 UTC

**Comment by johnwiesel** [comment] 2015-02-25 09:20
Thanks, this issue has not reoccurred as the older machine where the error appeared has since been retired anyway.
